import About from "@/components/About";
import Main from "@/components/Main";
import Skills from "@/components/Skills";
import Projects from "@/components/Projects";
import Head from "next/head";
import Image from "next/image";
import Contact from "@/components/Contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Shihas Backer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/navProfile.png" />
      </Head>
      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </div>
  );
}
